---
- name: common configuration
  hosts: all
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup admin node
  become: yes
  become_user: cephuser
  hosts: admin
  roles:
    - configure-admin

- name: copy admin key to nodes
  become: yes
  become_user: cephuser
  hosts: mon, osd
  roles:
    - copy-keys

- name: ceph-deploy setup
  hosts: admin
  roles:
    - ceph-deploy-setup

- name: deploy cluster
  become: true
  become_method: su
  become_user: cephuser
  become_flags: '-'
  hosts: admin
  roles:
    - deploy-ceph-cluster

- name: install REX-Ray
  hosts: osd
  roles:
    - rex-ray-installation
    - rex-ray-configuration

- name: install Docker
  hosts: osd
  roles:
    - docker-installation

- name: init Docker swarm
  hosts: node1
  roles:
    - docker-swarm-init

- name: add managers
  hosts: node2, node3 
  roles:
    - docker-swarm-add-manager
