---
- name: create partition
  parted:
    device: /dev/sda
    number: 1
    state: present
    part_start: 0%
    part_end: 100%
- name: format partition
  filesystem:
    fstype: xfs
    dev: /dev/sda
